"""add_is_active_column_to_tables

Revision ID: 88c32b2b47dd
Revises: 4e680359fa39
Create Date: 2025-06-03 14:19:08.108292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c32b2b47dd'
down_revision: Union[str, None] = '4e680359fa39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_equipment_is_active'), 'equipment', ['is_active'], unique=False)
    op.add_column('factories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_factories_is_active'), 'factories', ['is_active'], unique=False)
    op.add_column('sections', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_sections_is_active'), 'sections', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_is_active'), table_name='sections')
    op.drop_column('sections', 'is_active')
    op.drop_index(op.f('ix_factories_is_active'), table_name='factories')
    op.drop_column('factories', 'is_active')
    op.drop_index(op.f('ix_equipment_is_active'), table_name='equipment')
    op.drop_column('equipment', 'is_active')
    # ### end Alembic commands ###
